"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['TARGEST.png', 'TARGEST2.png', 'TARGEST3.png', 'requirements.txt', 'Gui.py', 'Targest.py', 'Targest2.py', 
'tempCodeRunnerFile.py']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
